####################################################
# sample config file for AnimeDriver.jl
####################################################
# settings to generate a new ms

mode: "uvfits"                                       # "vex", "uvfits", "manual" are the only allowed values
msname: "eht.ms"                                  # name of output ms 
telescopename: "VLBA"                                # preset telescope known to casa (not important since CASA is not used for predict; just an argument required for setconfig)
stations: "/home/iniyan/software/dev/Anime.jl/inputs/eht_2017.stations"     # CSV file with station parameters
casaanttemplate: "/home/iniyan/software/dev/Anime.jl/inputs/antenna_table.template"                 # Input CASA ANTENNA table to use as template
vex: "/home/iniyan/software/dev/Anime.jl/inputs/vexfiles/e17e11.vex"    # name of the VEX schedule to use for observing
uvfits: "/home/iniyan/software/dev/Anime.jl/inputs/uvfitsfiles/hops_lo_3601_M87+zbl-dtcal_selfcal.uvfits" # name of uvfits file to convert to ms
autocorr: false                                      # toggle whether to include autocorrelations
feed: "perfect R L"                                  # "perfect R L" or "perfect X Y"
shadowlimit: 1e-6                                    # maximum fraction of geometrically shadowed area before flagging occurs
elevationlimit: "10deg"                              # minimum elevation angle before flagging occurs
source:
  M87:
    RA: "12h30m49.42"                                # right ascension of source position in hours
    Dec: "+12.23.28.04"                              # declination of source position in degrees
    epoch: "J2000"                                   # "J2000" or "B1950"
scans: 5                                             # number of scans
scanlengths: [600.0, 600.0, 600.0, 600.0, 600.0]                              # list of lengths of each scan in seconds
scanlag: 180.0                                     # lag time between scans in seconds
exposure: 0.4                                          # integration time in seconds
stokes: "RR RL LR LL"                                # CASA understandable Stokes types to simulate (check official MS specification)
spw:
    centrefreq: [229.0e9]                            # centre frequency of spw in Hz
    bandwidth: [2e9]                               # bandwidth of spw in Hz
    channels: [16]                                   # number of channels in spw
starttime: "UTC,2021/04/28/00:00:00.00"              # starting time of the first scan in the observation

####################################################
# settings for wsclean predict

osfactor: 8191                                       # oversampling factor for WSClean
skymodel: "/home/iniyan/software/dev/Anime.jl/inputs/sourcemodels/point"       # HDF5 file or directory containing FITS files
polarized: false                                     # toggle source model polarization
channelgroups: 1                                     # number of groups to divide the channels into for computing source coherencies

####################################################
# common settings

correff: 0.88                                      # correlator efficiency for 2 quantization bits (use 0.636 for 1-bit)
corruptseed: 456                                     # seed to be used for generating random variables for corruptions (except for troposphere)
diagnostics: true                                  # generate diagnostic plots and logs

####################################################
# settings for atmospheric corruptions

troposphere:                                         # add troposphere
  enable: false
  wetonly: false                                     # add only the wet component
  attenuate: true                                   # signal attenuation due to opacity
  skynoise: true                                    # add tropospheric contribution to sky noise
  meandelays: true                                   # add mean delays
  fixdelays: false                                   # add fixed delays 
  turbulence: true                                  # add turbulent phases
  tropseed: 873256                                      # independent seed for generating random variables for troposphere

ionosphere:                                          # add ionosphere
  enable: false

####################################################
# beam and pointing settings

pointing:
  enable: true
  mode: "gp"                                         # "gp" (Gaussian processes) or "normal" (Gaussian)
  interval: 5.0                          # time interval (in seconds) after which to generate new pointing errors (<=0.0 for "mean(coherencetime)")
  scale: 100.0                                   # scale mixture parameter for long-term smoothness

####################################################
# settings for instrumental polarization

instrumentalpolarization: 
  enable: false                                       # add instrumental polarization
  mode: "gp"                                     # "gp" (Gaussian processes) or "normal" (Gaussian)
  visibilityframe: "sky"                             # visibilities are written out in "sky" frame; any other string => antenna frame

####################################################
# settings for gains

stationgains: 
  enable: false                                      # add antenna gains
  mode: "gp"                                     # "gp" or "normal"
bandpass: 
  enable: false                                      # add bandpass effects 
  bandpassfile: "/home/iniyan/software/dev/Anime.jl/inputs/eht_2017.bandpass" # csv file containing bandpass information for all stations

####################################################
# noise settings

thermalnoise: 
  enable: false                                      # toggle thermal noise
